EXE := lbc

BIN_DIR := bin
CFLAGS := -Mobjfpc -Px86_64 -g

.PHONY: all
all: lbc

.PHONY: lbc
lbc: src/lbc.pp
	@if not exist $(BIN_DIR)\ mkdir $(BIN_DIR)
	fpc $< -o"$(BIN_DIR)\$(EXE).exe" $(CFLAGS)

.PHONY: clean
clean: $(BIN_DIR)
	@del $<\$(EXE).exe
	@del /S "$<\*.o"
	@del /S "$<\*.ppu"

.PHONY: run
run: $(BIN_DIR)
	@echo on && echo:
	@cd $< && lbc.exe
